version: "3.2"

services:

  my-hub:
    # image: vikru/my-hub:v2.8.0-rc5
    # image: vikru/my-hub:v2.8.0-rc10
    image: vikru/my-hub-slim
    restart: always
    ports:
      - 9950:8000
    depends_on:
      - "postgres"      
    environment:      
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/hub1
      - AIRFLOW__HYPEROPT_MONGO=mongo://mongo:27017/testopt/jobs

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - mlflow:/home/admin/mlflow
      - /mnt/d/HighResolution:/home/admin/HighResolution
    secrets:
      - source: server.crt
        target: /cer.pem
      - source: server.key
        target: /key.pem
      - source: hub.cfg
        target: /defaults.cfg
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]        




  postgres:
    image: postgres:15.5
    restart: always    
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
        - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - pgdata:/var/lib/postgresql/data/pgdata

  mongo:
    image: mongo
    restart: always
    volumes:
        - mongodb:/data/db
        - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - "mongo"
    environment:
      - ME_CONFIG_SITE_BASEURL=/user/admin/mongo



secrets:
  server.crt:
      file: ./server.crt
  server.key:
      file: ./server.key
  hub.cfg:
    file: ./hub.cfg

volumes:
  mongodb:
  mongodb_config:
  pgdata:
  mlflow: