apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hub
  name: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hub
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hub
    spec:
      containers:
        - env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow:airflow@postgres:5432/hub1
            - name: AIRFLOW_HOME
              value: '/home/admin/airflow'  
            - name: HOME
              value: '/home/admin'                  
          image: vikru/my-hub:v2.8.0-rc6
          name: my-hub
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: "/cer.pem"
              name: hub-cfg
              subPath: crt
            - mountPath: "/key.pem"
              name: hub-cfg
              subPath: key
            - mountPath: "/defaults.cfg"
              name: hub-cfg
              subPath: cfg  
            - mountPath: "/home/admin/workflow/output"           
              name: output-data
      restartPolicy: Always
      volumes:
        - name: hub-cfg
          secret:
            secretName: hub-cfg
        - name: output-data
          persistentVolumeClaim:
            claimName: output-data


status: {}
