apiVersion: apps/v1
kind: Deployment
metadata:
  name: output-nfs-store
spec:
  replicas: 1
  selector:
    matchLabels:
      role: output-nfs-store
  template:
    metadata:
      labels:
        role: output-nfs-store
    spec:
      containers:
      - name: output-nfs-store
        image: gcr.io/google_containers/volume-nfs:0.8
        resources: {}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfsstore
      volumes:
        - name: nfsstore
          persistentVolumeClaim:
            claimName: output-nfs-store-data


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    role: output-nfs-store
  name: output-nfs-store-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}


---


apiVersion: v1
kind: Service
metadata:
  name: output-data-server
spec:
  type: ClusterIP
  clusterIP: 10.100.200.2
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: output-nfs-store


---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: output-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.100.200.2
    path: "/"


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: output-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi