name: Create Docker Image

on:
  release:
      types: [published]
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '').replace(/refs\/heads\/master\//,'');

    - name: Extract branch name
      shell: bash
      run: echo "${{ steps.tag.outputs.result }}"

    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: vikru/my-hub
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     dockerfile: core-container/Dockerfile  
    #     tags: "latest,${{ steps.extract_branch.outputs.branch }}"
