name: Create Docker Image

on:
  release:
      types: [published]
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        echo ::set-output name=TAG::${latest/master/$VERSION}
        echo $TAG

    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: vikru/my-hub
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     dockerfile: core-container/Dockerfile  
    #     tags: "${{ steps.get_version.outputs.VERSION }}"
